#spring:
#  application:
#    name: eureka-server
#  zipkin:
#    base-url: http://localhost:9411
#server:
#  port: 8761
#
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#  instance:
#    prefer-ip-address: true
#    hostname: localhost

#spring:
#  application:
#    name: eureka-server
#  zipkin:
#    base-url: http://localhost:9411
#  cloud:
#    discovery:
#      enabled: true
#
#server:
#  port: 8761
#
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#  instance:
#    prefer-ip-address: true
#    hostname: localhost


spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    hostname: localhost
